name = "caveful_games/stringdiff"
version = "0.2.0-rc.1"
description = "A string similarity metric diffing algorithm invented by splinestein for primitive chat bot use. Modified and uploaded for pesde"
authors = ["Spline", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/CavefulGames/stringdiff"
license = "MIT"
includes = ["pesde.toml", "LICENSE", "src/**", "README.md"]
private = true

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.8.9"
pesde = "^0.6.0"

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.11" }
multitarget = { name = "jiwonz/multitarget", version = "^0.4.0-rc.28" }
darklua = { name = "pesde/darklua", version = "^0.16.0" }
